CREATE DATABASE USUARIOS

USE USUARIOS

----------------
--TABLA EMPLEADO
----------------

CREATE TABLE EMPLEADO(
ID_EMPLEADO INT PRIMARY KEY,
NOMBRE_1 VARCHAR(15) NOT NULL,
NOMBRE_2 VARCHAR(15) NOT NULL,
APELLIDO_1 VARCHAR(15) NOT NULL,
APELLIDO_2 VARCHAR(15) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
GENERO VARCHAR(15) NOT NULL,
ESTADO_CIVIL VARCHAR(10) NOT NULL,
TELEFONO VARCHAR(15) NOT NULL,
NACIONALIDAD VARCHAR(15) NOT NULL,
FECHA_REGISTRO SMALLDATETIME NOT NULL,
CEDULA VARCHAR(10) NOT NULL,
EMAIL VARCHAR(15) NOT NULL
);

--------------------------------
--INSERTAR Y ACTUALIZAR EMPLEADO
--------------------------------

GO
CREATE PROCEDURE I_U_EMPLEADO
@ID_EMPLEADO INT,
@NOMBRE_1 VARCHAR(15),
@NOMBRE_2 VARCHAR(15),
@APELLIDO_1 VARCHAR(15),
@APELLIDO_2 VARCHAR(15),
@FECHA_NACIMIENTO DATE,
@GENERO VARCHAR(15),
@ESTADO_CIVIL VARCHAR(10),
@TELEFONO VARCHAR(15),
@NACIONALIDAD VARCHAR(15),
@FECHA_REGISTRO SMALLDATETIME,
@CEDULA VARCHAR(10),
@EMAIL VARCHAR(15)
AS
IF EXISTS (SELECT ID_EMPLEADO FROM EMPLEADO WHERE ID_EMPLEADO = @ID_EMPLEADO)
BEGIN
UPDATE EMPLEADO SET ID_EMPLEADO = @ID_EMPLEADO, NOMBRE_1 = @NOMBRE_1, NOMBRE_2 = @NOMBRE_2, APELLIDO_1 = @APELLIDO_1, APELLIDO_2 = @APELLIDO_2, FECHA_NACIMIENTO = @FECHA_NACIMIENTO, GENERO = @GENERO, ESTADO_CIVIL = @ESTADO_CIVIL, TELEFONO = @TELEFONO, NACIONALIDAD = @NACIONALIDAD, FECHA_REGISTRO = @FECHA_REGISTRO, CEDULA = @CEDULA, EMAIL = @EMAIL)
WHERE ID_EMPLEADO = @ID_EMPLEADO
END
ELSE
BEGIN
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_1, NOMBRE_2, APELLIDO_1, APELLIDO_2, FECHA_NACIMIENTO, GENERO, ESTADO_CIVIL, TELEFONO, NACIONALIDAD, FECHA_REGISTRO, CEDULA, EMAIL)
VALUES (@ID_EMPLEADO, @NOMBRE_1, @NOMBRE_2, @APELLIDO_1, @APELLIDO_2, @FECHA_NACIMIENTO, @GENERO, @ESTADO_CIVIL, @TELEFONO, @NACIONALIDAD, @FECHA_REGISTRO, @CEDULA, @EMAIL)
END

INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_1, NOMBRE_2, APELLIDO_1, APELLIDO_2, FECHA_NACIMIENTO, GENERO, ESTADO_CIVIL, TELEFONO, NACIONALIDAD, FECHA_REGISTRO, CEDULA, EMAIL)
VALUES (@ID_EMPLEADO, @NOMBRE_1, @NOMBRE_2, @APELLIDO_1, @APELLIDO_2, @FECHA_NACIMIENTO, @GENERO, @ESTADO_CIVIL, @TELEFONO, @NACIONALIDAD, @FECHA_REGISTRO, @CEDULA, @EMAIL)

EXEC I_U_EMPLEADO

-----------------
--BUSCAR EMPLEADO
-----------------

GO
CREATE PROCEDURE F_EMPLEADO
@F_A_C_N VARCHAR(20)
AS
SELECT * FROM EMPLEADO
WHERE APELLIDO_1 = @F_A_C_N OR CEDULA = @F_A_C_N OR NOMBRE_1 = @F_A_C_N

EXEC F_EMPLEADO

----------------------------------------------
--PROCEDIMIENTO PARA BUSCAR MODULOS DE USUARIO
----------------------------------------------

GO
CREATE PROCEDURE F_MODULOS_USUARIO
@NOMBRE_USUARIO VARCHAR(20)
AS
SELECT USUARIO.NOMBRE_USUARIO USUARIO MODULOS.NOMBRE_MODULO MODULO
FROM MODULOS_USUARIO
INNER JOIN USUARIO
ON MODULOS_USUARIO.ID_USUARIO = USUARIO.ID_USUARIO = USUARIO.ID_USUARIO
INNER JOIN MODULOS
ON MODULOS_USUARIO.ID_MODULOS = MODULOS.ID_MODULOS
WHERE USUARIO.NOMBRE_USUARIO = '@NOMBRE_USUARIO'

EXEC F_MODULOS_USUARIO

---------------
--TABLA MODULOS
---------------

CREATE TABLE MODULOS(
ID_MODULO INT PRIMARY KEY,
NOMBRE_MODULO VARCHAR(15) NOT NULL,
FECHA_REGISTRO SMALLDATETIME NOT NULL
);

------------------
--INSERTAR MODULOS
------------------

GO
CREATE PROCEDURE I_MODULOS
@ID_MODULO INT,
@NOMBRE_MODULO VARCHAR(15),
@FECHA_REGISTRO SMALLDATETIME
AS
INSERT INTO MODULOS (ID_MODULO, NOMBRE_MODULO, FECHA_REGISTRO)
VALUES (@ID_MODULO, @NOMBRE_MODULO, @FECHA_REGISTRO)

EXEC I_MODULOS

--------------------
--ACTUALIZAR MODULOS
--------------------

GO
CREATE PROCEDURE U_MODULOS
@ID_MODULO INT,
@NOMBRE_MODULO VARCHAR(15),
@FECHA_REGISTRO SMALLDATETIME
AS
UPDATE MODULOS SET ID_MODULO = @ID_MODULO, NOMBRE_MODULO = @NOMBRE_MODULO, FECHA_REGISTRO = @FECHA_REGISTRO

EXEC U_MODULOS

------------------
--ELIMINAR MODULOS
------------------

GO
CREATE PROCEDURE D_MODULOS
@ID_MODULO INT,
@NOMBRE_MODULO VARCHAR(15),
@FECHA_REGISTRO SMALLDATETIME
AS
DELETE FROM MODULOS WHERE ID_MODULO = @ID_MODULO

EXEC D_MODULOS

----------------
--BUSCAR MODULOS
----------------

GO
CREATE PROCEDURE F_MODULOS
@ID_MODULO INT
AS
SELECT * FROM MODULOS WHERE ID_MODULO = @ID_MODULO

EXEC F_MODULOS

---------------
--TABLA USUARIO
---------------

CREATE TABLE USUARIO(
ID_USUARIO INT PRIMARY KEY,
ID_EMPLEADO INT FOREIGN KEY REFERENCES EMPLEADO (ID_EMPLEADO),
NIVEL INT NOT NULL,
NOMBRE_USUARIO VARCHAR(15) NOT NULL,
CONTRASEÑA VARCHAR(15) NOT NULL,
ESTADO VARCHAR(15) NOT NULL,
FECHA_CREACION SMALLDATETIME NOT NULL
);

EXEC USUARIO

------------------
--INSERTAR USUARIO
------------------

GO
CREATE PROCEDURE I_USUARIO
@ID_EMPLEADO INT,
@NIVEL INT,
@NOMBRE_USUARIO VARCHAR(15),
@CONTRASEÑA VARCHAR(15),
@ESTADO VARCHAR(15),
@FECHA_CREACION SMALLDATETIME
AS
INSERT INTO USUARIOS (ID_USUARIO, ID_EMPLEADO, NIVEL, NOMBRE_USUARIO, CONTRASEÑA, ESTADO, FECHA_CREACION)
VALUES (@ID_USUARIO, @ID_EMPLEADO, @NIVEL, @NOMBRE_USUARIO, @CONTRASEÑA, @ESTADO, @FECHA_CREACION)

EXEC I_USUARIO

--------------------
--ACTUALIZAR USUARIO
--------------------

GO
CREATE PROCEDURE U_USUARIO
@ID_EMPLEADO INT,
@NIVEL INT,
@NOMBRE_USUARIO VARCHAR(15),
@CONTRASEÑA VARCHAR(15),
@ESTADO VARCHAR(15),
@FECHA_CREACION SMALLDATETIME
AS
UPDATE USUARIOS SET ID_EMPLEADO = @ID_EMPLEADO, NIVEL = @NIVEL, NOMBRE_USUARIO = @NOMBRE_USUARIO, CONTRASEÑA = @CONTRASEÑA, ESTADO = @ESTADO, FECHA_CREACION = @FECHA_CREACION
WHERE ID_EMPLEADO = @ID_EMPLEADO

EXEC U_USUARIO

------------------
--ELIMINAR USUARIO
------------------

GO
CREATE PROCEDURE D_USUARIO
@ID_EMPLEADO INT
AS
DELETE FROM USUARIO WHERE ID_EMPLEADO = @ID_EMPLEADO

GO
CREATE PROCEDURE F_USUARIO
@ID_USUARIO INT
AS
SELECT * FROM USUARIO WHERE ID_USUARIO = @ID_USUARIO

EXEC D_USUARIO

-----------------------
--TABLA MODULOS_USUARIO
-----------------------

CREATE TABLE MODULOS_USUARIO(
ID_MODULOS_USUARIO INT PRIMARY KEY,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO),
ID_MODULO INT FOREIGN KEY REFERENCES MODULOS (ID_MODULO),
NOMBRE_MODULO VARCHAR(15) NOT NULL,
FECHA_REGISTRO SMALLDATETIME NOT NULL
);

EXEC MODULOS_USUARIO

--------------------------
--INSERTAR MODULOS USUARIO
--------------------------

GO
CREATE PROCEDURE I_MODULOS_USUARIO
@ID_MODULOS_USUARIO INT,
@ID_USUARIO INT,
@ID_MODULO INT,
@NOMBRE_MODULO VARCHAR(15),
@FECHA_REGISTRO SMALLDATETIME
AS
INSERT INTO MODULOS_USUARIO (ID_MODULOS_USUARIO, ID_USUARIO, ID_MODULO, NOMBRE_MODULO, FECHA_REGISTRO)
VALUES (@ID_MODULOS_USUARIO, @ID_USUARIO, @ID_MODULO, @NOMBRE_MODULO, @FECHA_REGISTRO)

EXEC I_MODULOS_USUARIO

----------------------------
--ACTUALIZAR MODULOS USUARIO
----------------------------

GO
CREATE PROCEDURE U_MODULOS_USUARIO
@ID_MODULOS_USUARIO INT,
@ID_USUARIO INT,
@ID_MODULO INT,
@FECHA_REGISTRO SMALLDATETIME
AS
UPDATE MODULOS_USUARIO SET ID_MODULOS_USUARIO = @ID_MODULOS_USUARIO, ID_USUARIO = @ID_USUARIO, ID_MODULO = @ID_MODULO, FECHA_REGISTRO = @FECHA_REGISTRO
WHERE ID_MODULOS_USUARIO = @ID_MODULOS_USUARIO

U_MODULOS_USUARIO

--------------------------
--ELIMINAR MODULOS USUARIO
--------------------------

GO
CREATE PROCEDURE D_MODULOS_USUARIO
@ID_MODULOS_USUARIOS INT
AS
DELETE FROM D_MODULOS_USUARIO WHERE ID_MODULOS_USUARIO = @ID_MODULOS_USUARIO

EXEC D_MODULOS_USUARIO

------------------------
--BUSCAR MODULOS USUARIO
------------------------

GO
CREATE PROCEDURE F_MODULOS_USUARIO
@ID_MODULOS_USUARIO INT
AS
SELECT * FROM MODULOS_USUARIO WHERE ID_MODULOS_USUARIO = @ID_MODULOS_USUARIO

EXEC F_MODULOS_USUARIO