USE TIENDA

CREATE TABLE USUARIO(
ID_USUARIO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NIVEL INT NOT NULL,
NOMBRE_USUARIO VARCHAR(15) NOT NULL,
CONTRASEÑA VARCHAR(20) NOT NULL,
ESTADO VARCHAR(15) NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL
);

CREATE TABLE PROVEEDOR(
ID_PROVEEDOR INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(15) NOT NULL,
APELLIDO VARCHAR(15) NOT NULL,
NOMBRE_CAMPAÑA VARCHAR(20) NOT NULL,
TELEFONO VARCHAR(15) NOT NULL,
CUENTA VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20) NOT NULL,
RNC VARCHAR(20) NOT NULL,
WEB VARCHAR(20) NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO) NOT NULL
);

CREATE TABLE ARTICULO(
ID_ARTICULO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOMBRE_APELLIDO VARCHAR(30) NOT NULL,
MARCA VARCHAR(15) NOT NULL,
DESCRIPCION VARCHAR(30) NOT NULL,
TIPO VARCHAR(15) NOT NULL,
PRESENTACION VARCHAR(20) NOT NULL,
FECHA_EXP DATE NOT NULL,
STOCK_MIN VARCHAR(20) NOT NULL,
COSTO MONEY NOT NULL,
PRECIO_VENTA MONEY NOT NULL,
BENEFICIO VARCHAR(20) NOT NULL,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO) NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL,
ITBIS FLOAT NOT NULL,
ID_PROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR (ID_PROVEEDOR) NOT NULL
);

CREATE TABLE FACTURA(
ID_FACTURA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NUMERO_FACTURA INT NOT NULL,
ID_PROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR (ID_PROVEEDOR) NOT NULL,
TOTAL_PAGAR MONEY NOT NULL,
NCF VARCHAR(20) NOT NULL,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO) NOT NULL
);

CREATE TABLE DETALLE_FACTURA(
ID_DETALLE INT IDENTITY(1,1) PRIMARY KEY,
ID_FACTURA INT FOREIGN KEY REFERENCES FACTURA (ID_FACTURA) NOT NULL,
ID_ARTICULO INT FOREIGN KEY REFERENCES ARTICULO (ID_ARTICULO) NOT NULL,
CANTIDAD INT NOT NULL,
COSTO MONEY NOT NULL
);