CREATE DATABASE ESCUELA
USE ESCUELA

--TABLA CARRERA
CREATE TABLE CARRERA(
clave_c INT,
nombre_c VARCHAR (50),
durac_c FLOAT,
CONSTRAINT pk_cc PRIMARY KEY(clave_c)
)

--TABLA MATERIA
CREATE TABLE MATERIA(
clave_m INT,
nom_m VARCHAR(50),
cred_m FLOAT,
CONSTRAINT pk_cm PRIMARY KEY(clave_m)
)

--TABLA PROFESOR
CREATE TABLE PROFESOR(
clave_p INT,
nom_p VARCHAR(150),
dir_p VARCHAR(200),
tel_p BIGINT,
hor_p DATETIME,
CONSTRAINT pk_cp PRIMARY KEY(clave_p)
)

/*TABLA ALUMNO
(CON CLAVE FORANEA)*/
CREATE TABLE ALUMNO(
mat_alu INT,
nom_alu VARCHAR(150),
edad_alu INT,
sem_alu INT,
gen_alu VARCHAR(10),
clave_c1 INT,
CONSTRAINT pk_calu PRIMARY KEY(mat_alu),
CONSTRAINT pk_fc1 FOREIGN KEY(clave_c1) REFERENCES CARRERA (clave_c)
)

--TABLA ALUMNO-PROFESOR
CREATE TABLE ALU_PRO(
mat_alu1 INT,
clave_p1 INT,
CONSTRAINT fk_falu1 FOREIGN KEY(mat_alu1) REFERENCES ALUMNO(mat_alu),
CONSTRAINT fk_fp1 FOREIGN KEY(clave_p1) REFERENCES PROFESOR(clave_p)
)

--TABLA MATERIA-ALUMNO
CREATE TABLE MAT_ALU(
clave_m1 INT,
mat_alu2 INT,
CONSTRAINT fk_fm1 FOREIGN KEY (clave_m1) REFERENCES MATERIA (clave_m),
CONSTRAINT fk_falu2 FOREIGN KEY (mat_alu2) REFERENCES ALUMNO (mat_alu)
)

--TABLA MATERIA-PROFESOR
CREATE TABLE MAT_PRO(
clave_m2 INT,
clave_p2 INT,
CONSTRAINT fk_fm2 FOREIGN KEY(clave_m2) REFERENCES MATERIA(clave_m),
CONSTRAINT fk_fp2 FOREIGN KEY(clave_p2) REFERENCES PROFESOR(clave_p)
)