--SANTIAGO NATHANAEL LARA [2019-0207]

USE CURSO

--------
--INSERT
--------

GO
CREATE PROCEDURE I_CLIENTES
@CLIENTE_NO INT,
@NOMBRE VARCHAR(15),
@LOCALIDAD VARCHAR(15),
@VENDEDOR_NO INT,
@DEBE MONEY,
@HABER MONEY,
@LIMITE_CREDITO MONEY
AS
INSERT INTO CLIENTES (CLIENTE_NO, NOMBRE, LOCALIDAD, VENDEDOR_NO, DEBE, HABER, LIMITE_CREDITO)
VALUES (@CLIENTE_NO, @NOMBRE, @LOCALIDAD, @VENDEDOR_NO, @DEBE, @HABER, @LIMITE_CREDITO)

GO
CREATE PROCEDURE I_DEPARTAMENTOS
@DEP_NO INT,
@DNOMBRE VARCHAR(15),
@LOCALIDAD VARCHAR(15)
AS
INSERT INTO DEPARTAMENTOS (DEP_NO, DNOMBRE, LOCALIDAD)
VALUES (@DEP_NO, @DNOMBRE, @LOCALIDAD)

GO
CREATE PROCEDURE I_EMPLEADOS
@EMP_NO INT,
@APELLIDO VARCHAR(15),
@OFICIO VARCHAR(15),
@DIRECTOR INT,
@FECHA_ALTA DATETIME2,
@SALARIO MONEY,
@COMISION MONEY,
@DEP_NO INT
AS
INSERT INTO EMPLEADOS (EMP_NO, APELLIDO, OFICIO, DIRECTOR, FECHA_ALTA, SALARIO, COMISION, DEP_NO)
VALUES (@EMP_NO ,@APELLIDO, @OFICIO, @DIRECTOR, @FECHA_ALTA, @SALARIO, @COMISION, @DEP_NO)

GO
CREATE PROCEDURE I_GERENTE_GENERAL
@COD_GER INT,
@NOM_GER VARCHAR(15),
@APE_GER VARCHAR(15),
@FEC_GER DATE,
@DIR_GER VARCHAR(15)
AS
INSERT INTO GERENTE_GENERAL (COD_GER, NOM_GER, APE_GER, FEC_GER, DIR_GER)
VALUES (@COD_GER, @NOM_GER, @APE_GER, @FEC_GER, @DIR_GER)

GO
CREATE PROCEDURE I_PEDIDOS
@PEDIDO_NO INT,
@PRODUCTO_NO INT,
@CLIENTE_NO INT,
@UNIDADES INT,
@FECHA_PEDIDO DATETIME2
AS
INSERT INTO PEDIDOS (PEDIDO_NO, PRODUCTO_NO, CLIENTE_NO, UNIDADES, FECHA_PEDIDO)
VALUES (@PEDIDO_NO, @PRODUCTO_NO, @CLIENTE_NO, @UNIDADES, @FECHA_PEDIDO)

GO
CREATE PROCEDURE I_PRODUCTOS
@PRODUCTO_NO INT,
@DESCRIPCION VARCHAR(20),
@PRECIO_ACTUAL MONEY,
@STOCK_DISPONIBLE INT
AS
INSERT INTO PRODUCTOS (PRODUCTO_NO, DESCRIPCION, PRECIO_ACTUAL, STOCK_DISPONIBLE)
VALUES (@PRODUCTO_NO, @DESCRIPCION, @PRECIO_ACTUAL, @STOCK_DISPONIBLE)

------
--FIND
------

GO
CREATE PROCEDURE F_CLIENTES
@CLIENTE_NO INT
AS
SELECT * FROM CLIENTES WHERE CLIENTE_NO = @CLIENTE_NO

GO
CREATE PROCEDURE F_DEPARTAMENTOS
@DEP_NO INT
AS
SELECT * FROM DEPARTAMENTOS WHERE DEP_NO = @DEP_NO

GO
CREATE PROCEDURE F_EMPLEADOS
@EMP_NO INT
AS
SELECT * FROM EMPLEADOS WHERE EMP_NO = @EMP_NO

GO
CREATE PROCEDURE F_GERENTE_GENERAL
@COD_GER INT
AS
SELECT * FROM GERENTE_GENERAL WHERE COD_GER = @COD_GER

GO
CREATE PROCEDURE F_PEDIDOS
@PEDIDO_NO INT
AS
SELECT * FROM PEDIDOS WHERE PEDIDO_NO = @PEDIDO_NO

GO
CREATE PROCEDURE F_PRODUCTOS
@PRODUCTO_NO INT
AS
SELECT * FROM PRODUCTOS WHERE PRODUCTO_NO = @PRODUCTO_NO

--------
--DELETE
--------

GO
CREATE PROCEDURE D_CLIENTES
@CLIENTE_NO INT
AS
DELETE FROM CLIENTES WHERE CLIENTE_NO = @CLIENTE_NO

GO
CREATE PROCEDURE D_DEPARTAMENTOS
@DEP_NO INT
AS
DELETE FROM DEPARTAMENTOS WHERE DEP_NO = @DEP_NO

GO
CREATE PROCEDURE D_EMPLEADOS
@EMP_NO INT
AS
DELETE FROM EMPLEADOS WHERE EMP_NO = @EMP_NO

GO
CREATE PROCEDURE D_GERENTE_GENERAL
@COD_GER INT
AS
DELETE FROM GERENTE_GENERAL WHERE cod_ger=@COD_GER

GO
CREATE PROCEDURE D_PEDIDOS
@PEDIDO_NO INT
AS
DELETE FROM PEDIDOS WHERE PEDIDO_NO = @PEDIDO_NO

GO
CREATE PROCEDURE D_PRODUCTOS
@PRODUCTO_NO INT
AS
DELETE FROM PRODUCTOS WHERE PRODUCTO_NO = @PRODUCTO_NO

--------
--UPDATE
--------
GO
CREATE PROCEDURE U_CLIENTES
@CLIENTE_NO INT,
@NOMBRE VARCHAR(15),
@LOCALIDAD VARCHAR(15),
@VENDEDOR_NO INT,
@DEBE MONEY,
@HABER MONEY,
@LIMITE_CREDITO MONEY
AS
UPDATE CLIENTES SET CLIENTE_NO = @CLIENTE_NO, NOMBRE= @NOMBRE, LOCALIDAD = @LOCALIDAD, VENDEDOR_NO = @VENDEDOR_NO, DEBE = @DEBE, HABER = @HABER, LIMITE_CREDITO = @LIMITE_CREDITO
WHERE CLIENTE_NO = @CLIENTE_NO

GO
CREATE PROCEDURE U_DEPARTAMENTOS
@DEP_NO INT,
@DNOMBRE VARCHAR(15),
@LOCALIDAD VARCHAR(15)
AS
UPDATE DEPARTAMENTOS SET DEP_NO = @DEP_NO, DNOMBRE = @DNOMBRE, LOCALIDAD = @LOCALIDAD
WHERE DEP_NO=@DEP_NO

GO
CREATE PROCEDURE U_EMPLEADOS
@EMP_NO INT,
@APELLIDO VARCHAR(15),
@OFICIO VARCHAR(15),
@DIRECTOR INT,
@FECHA_ALTA DATETIME2,
@SALARIO MONEY,
@COMISION MONEY,
@DEP_NO INT
AS
UPDATE EMPLEADOS SET EMP_NO = @EMP_NO, APELLIDO = @APELLIDO, OFICIO = @OFICIO, DIRECTOR = @DIRECTOR, FECHA_ALTA = @FECHA_ALTA, SALARIO = @SALARIO, COMISION = @COMISION, DEP_NO = @DEP_NO
WHERE EMP_NO = @EMP_NO

GO
CREATE PROCEDURE U_GERENTE_GENERAL
@COD_GER INT,
@NOM_GER VARCHAR(15),
@APE_GER VARCHAR(15),
@FEC_GER DATE,
@DIR_GER VARCHAR(15)
AS
UPDATE GERENTE_GENERAL SET COD_GER = @COD_GER, NOM_GER = @NOM_GER, APE_GER = @APE_GER, FEC_GER = @FEC_GER, DIR_GER = @DIR_GER
WHERE cod_ger = @COD_GER

GO
CREATE PROCEDURE U_PEDIDOS
@PEDIDO_NO INT,
@PRODUCTO_NO INT,
@CLIENTE_NO INT,
@UNIDADES INT,
@FECHA_PEDIDO DATETIME2
AS
UPDATE PEDIDOS SET PEDIDO_NO = @PEDIDO_NO, PRODUCTO_NO = @PRODUCTO_NO, CLIENTE_NO = @CLIENTE_NO, UNIDADES = @UNIDADES, FECHA_PEDIDO = @FECHA_PEDIDO
WHERE PEDIDO_NO = @PEDIDO_NO

GO
CREATE PROCEDURE U_PRODUCTOS
@PRODUCTO_NO INT,
@DESCRIPCION VARCHAR(20),
@PRECIO_ACTUAL MONEY,
@STOCK_DISPONIBLE INT
AS
UPDATE PRODUCTOS SET PRODUCTO_NO = @PRODUCTO_NO, DESCRIPCION = @DESCRIPCION, PRECIO_ACTUAL = @PRECIO_ACTUAL, STOCK_DISPONIBLE = @STOCK_DISPONIBLE
WHERE PRODUCTO_NO = @PRODUCTO_NO

--SANTIAGO NATHANAEL LARA [2019-0207]