CREATE TABLE USUARIO(
ID_USUARIO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NIVEL INT NOT NULL,
NOMBRE_USUARIO VARCHAR(15) NOT NULL,
CONTRASEÑA VARCHAR(20) NOT NULL,
ESTADO VARCHAR(15) NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL
);

CREATE TABLE PROVEEDOR(
ID_PROVEEDOR INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(15) NOT NULL,
APELLIDO VARCHAR(15) NOT NULL,
NOMBRE_CAMPAÑA VARCHAR(20) NOT NULL,
TELEFONO VARCHAR(15) NOT NULL,
CUENTA VARCHAR(20) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
RNC VARCHAR(20) NOT NULL,
WEB VARCHAR(20) NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO) NOT NULL
);

CREATE TABLE PROVEEDOR_HISTORIAL(
ID_PROVEEDOR INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(15) NOT NULL,
APELLIDO VARCHAR(15) NOT NULL,
NOMBRE_CAMPAÑA VARCHAR(20) NOT NULL,
TELEFONO VARCHAR(15) NOT NULL,
CUENTA VARCHAR(20) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
RNC VARCHAR(20) NOT NULL,
WEB VARCHAR(20) NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO) NOT NULL
);

CREATE TABLE ARTICULO(
ID_ARTICULO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
MARCA VARCHAR(15) NOT NULL,
DESCRIPCION VARCHAR(80) NOT NULL,
TIPO VARCHAR(15) NOT NULL,
PRESENTACION VARCHAR(20) NOT NULL,
FECHA_EXP DATE NOT NULL,
STOCK_MIN VARCHAR(20) NOT NULL,
COSTO MONEY NOT NULL,
PRECIO_VENTA MONEY NOT NULL,
BENEFICIO VARCHAR(20) NOT NULL,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO) NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL,
ITBIS FLOAT NOT NULL,
ID_PROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR (ID_PROVEEDOR) NOT NULL,
CANTIDAD INT NOT NULL
);

CREATE TABLE FACTURA(
ID_FACTURA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NUMERO_FACTURA INT NOT NULL,
ID_PROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR (ID_PROVEEDOR) NOT NULL,
TOTAL_PAGAR MONEY NOT NULL,
NCF VARCHAR(20) NOT NULL,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO) NOT NULL
);

CREATE TABLE DETALLE_FACTURA(
ID_DETALLE INT IDENTITY(1,1) PRIMARY KEY,
ID_FACTURA INT FOREIGN KEY REFERENCES FACTURA (ID_FACTURA) NOT NULL,
ID_ARTICULO INT FOREIGN KEY REFERENCES ARTICULO (ID_ARTICULO) NOT NULL,
CANTIDAD INT NOT NULL,
COSTO MONEY NOT NULL
);


/*INSERTAR REGISTROS*/
INSERT INTO USUARIO
(
NIVEL,
NOMBRE_USUARIO,
CONTRASEñA,
ESTADO,
FECHA_REGISTRO
)
VALUES
(
3,
'USR_NATHANAEL1',
'R?dG#2bYq=b-7-/,XN>n',
'COMPLETED',
GETDATE()
),
(
1,
'USR_RUBIUSXR1',
'Y5dG#2bZq3b-7-4S6R4',
'PENDING',
GETDATE()
)

INSERT INTO PROVEEDOR
(
NOMBRE, APELLIDO, NOMBRE_CAMPAÑA,
TELEFONO,
CUENTA,
EMAIL,
RNC,
WEB,
FECHA_REGISTRO,
ID_USUARIO
)
VALUES
(
'NATHANAEL',
'GUTIERREZ',
'NATHANAEL & ASOC',
'8094256042',
'5841-5559-5641-5648',
'NATHANAELYASOC10@YAHOO.COM',
'954788896644',
'WWW.NANDASOC.COM.DO',
GETDATE(),
1
),
(
'KAREN',
'GUTIERREZ',
'KAREN CO',
'9474256222',
'4844-5654-1231-8888',
'KARENCO126@KARENCO.COM',
'4956786666641',
'WWW.KARENCO.ORG',
GETDATE(),
1
),
(
'CARMEN',
'REYES',
'REYES S.A',
'8474256229',
'6444-5654-1231-8831',
'C.REYES@GMAIL.COM',
'4956786666646',
'WWW.CARMENCARMEN.DO',
GETDATE(),
1
),
(
'ROBERTO',
'HERNANDEZ',
'LG',
'1742562298',
'1133-5654-1231-8814',
'ROBERTOLG@LG.COM',
'1356786666649',
'WWW.LG.COM',
GETDATE(),
1
)

INSERT INTO ARTICULO
(
NOMBRE,
MARCA,
DESCRIPCION,
TIPO,
PRESENTACION,
FECHA_EXP,
STOCK_MIN,
COSTO,
PRECIO_VENTA,
BENEFICIO,
ID_USUARIO,
FECHA_REGISTRO,
ITBIS,
ID_PROVEEDOR,
CANTIDAD
)
VALUES
(
'LG THINQ',
'LG',
'TV 50'' | UHD 4K SMART TV | Ultra HD LED |',
'UHD',
'50"',
'2025-2-1',
10,
1000,
1199.99,
199.99,
1,
GETDATE(),
18,
3,
20
),
(
'OLED TV 77"',
'LG',
'OLED TV 77" 4K | Pixeles con Auto- Iluminación | ',
'OLED/UHD 4K',
'77"',
'2025-3-1',
10,
2000,
2499.99,
499.99,
2,
GETDATE(),
18,
3,
20
)

INSERT INTO FACTURA
(
NUMERO_FACTURA,
ID_PROVEEDOR,
TOTAL_PAGAR,
NCF,
ID_USUARIO
)
VALUES
(
2000101,
1,
1199.99,
'123456789123',
1
),
(
2000103,
1,
2499.99,
'129996789244',
2
)
INSERT INTO DETALLE_FACTURA
(
ID_FACTURA,
ID_ARTICULO,
CANTIDAD,
COSTO
)
values
(
1,
1,
3,
5999.97
),
(
1,
2,
1,
2499.99
)


select * from usuario
select * from proveedor
select * from articulo
select * from factura
select * from detalle_factura
select * from proveedor_historial

