USE CURSO

CREATE TABLE ORDENES(
PEDIDO_NO INT NOT NULL,
ORDENES INT NOT NULL,
FECHA_REG DATETIME,
);

GO
CREATE TRIGGER ORDENES_PEDIDOS
ON PEDIDOS
AFTER UPDATE
AS
BEGIN

DECLARE @PEDIDO_NO INT,
@ORDENES INT

SET @PEDIDO_NO = (SELECT PEDIDO_NO FROM INSERTED)
SET @ORDENES = (SELECT UNIDADES FROM INSERTED)

IF UPDATE (UNIDADES)
BEGIN
INSERT INTO ORDENES
(PEDIDO_NO, ORDENES, FECHA_REG) VALUES (@PEDIDO_NO, @ORDENES, GETDATE())
END

END

UPDATE PEDIDOS
SET UNIDADES = UNIDADES - 1
WHERE PEDIDO_NO = 1000

SELECT * FROM PEDIDOS